# Open nvim scratchpad
# exec --no-startup-id sh -c 'wezterm start --class "scratch_nvim" nvim ~/scratch.txt'
exec --no-startup-id sh -c 'ghostty --class=i3.scratch -e nvim ~/scratch.txt'

for_window [class="i3.scratch"] move to scratchpad, border 1pixel, resize set 35ppt 60ppt, move position 64ppt 20ppt

bindsym $mod+S scratchpad show; sticky enable

