#!/usr/bin/env bash

[ -z "$DOTFILES" ] && export DOTFILES="$HOME/dotfiles"

show_help() {
    echo "USAGE:"
    echo "    dot [OPTIONS]"
    echo -e "\nOPTIONS:"
    echo "    -h, --help                Show this help message"
    echo "    -i, --init, --install     Install/update required packages"
    echo "    -l, --linux               Set up Linux-specific configurations"
    echo "    -m, --macos               Set up MacOS-specific configurations"
    echo "    -w, --windows             Set up Windows-specific configurations"
    exit
}

options=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            ;;
        -l|--linux)
            options+=('--linux')
            ;;
        -m|--macos)
            options+=('--macos')
            ;;
        -w|--windows)
            options+=('--windows')
            ;;
        *) echo "Unknown option: $1"
            exit
            ;;
    esac
    shift
done

pushd "$DOTFILES" > /dev/null || exit
git pull
./stow.sh "${options[@]}"
popd > /dev/null || exit

