#!/usr/bin/env bash

[ -z "$DOTFILES" ] && export DOTFILES="$HOME/dotfiles"

show_help() {
    echo "USAGE:"
    echo "    dot [OPTIONS]"
    echo -e "\nOPTIONS:"
    echo "    -h, --help                Show this help message"
    echo "    -m, --macos               Set up MacOS-specific configurations"
    echo "    -o, --omarchy             Set up Omarchy-specific configurations"
    echo "    -u, --ubuntu              Set up Ubuntu-specific configurations"
    echo "    -w, --windows             Set up Windows-specific configurations"
    exit
}

options=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            ;;
        -m|--macos)
            options+=('--macos')
            ;;
        -o|--omarchy)
            options+=('--omarchy')
            ;;
        -u|--ubuntu)
            options+=('--ubuntu')
            ;;
        -w|--windows)
            options+=('--windows')
            ;;
        *)
            echo "Unknown option: $1"
            exit
            ;;
    esac
    shift
done

pushd "$DOTFILES" > /dev/null || exit
git pull > /dev/null
./stow.sh "${options[@]}"
popd > /dev/null || exit

