#!/usr/bin/env bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: loc [ext1[,ext2[...]] [dir]"
    echo "Examples:"
    echo "    loc"
    echo "    loc js,ts"
    echo "    loc js,ts src"
elif [[ -n "$1" && -n "$2" ]]; then
    cloc --include-ext="$1" --vcs git --exclude-dir=archive,bin,build,dist,obj,node_modules "$2"
elif [[ -d "$1" ]]; then
    cloc --vcs git --exclude-dir=archive,bin,build,dist,obj,node_modules "$1"
elif [[ -n "$1" && -z "$2" ]]; then
    cloc --include-ext="$1" --vcs git --exclude-dir=archive,bin,build,dist,obj,node_modules .
else
    cloc --vcs git --exclude-dir=archive,bin,build,dist,obj,node_modules .
fi
