#!/usr/bin/env bash

confirm() {
    printf "No\nYes\n" \
        | fzf \
        --header="Kill session $1?" \
        --border=none \
        --cycle \
        --gutter ' ' \
        --color='current-fg:#89b4fa,current-bg:#1c1c2b,pointer:#1c1c2b'
}

selected=$(tmux list-sessions -F '#{session_name}' \
    | fzf --reverse --header 'Kill session')

[[ ! $selected ]] && exit 0

if [[ $(confirm "$selected") == "Yes" ]]; then
    tmux kill-session -t "$selected"
fi
