#!/usr/bin/env bash

confirm() {
    printf "No\nYes\n" \
        | fzf \
        --style full \
        --header="Kill session $1?" \
        --header-border inline \
        --gutter ' '
}

selected=$(tmux list-sessions -F '#{session_name}' | fzf --style full --header 'Kill session' --header-border inline)

[[ ! $selected ]] && exit 0

if [[ $(confirm "$selected") == "Yes" ]]; then
    tmux kill-session -t "$selected"
fi
