#!/usr/bin/env bash
# shellcheck disable=2154

if [[ $(uname -a) != *mint* ]]; then
    exit 0
fi

sudo apt-add-repository -y ppa:yktooo/ppa
sudo apt update
sudo apt install -y indicator-sound-switcher
